### PR TITLE
Add UR30 support

### LINKED ISSUE #898: Support UR30
### Feature summary

Add UR30 to possible starting configurations. Same as #797

### Tasks
*To complete this issue involves*
- [ ] Implement the feature
- [ ] Make documentation

### PR DESCRIPTION
**Pull request by fmauch**
Resolves #898

### CODE REVIEW

**Comment by fmauch** [comment]
At the moment we don't have a URSim available for the UR30. I decided to not explicitly note this in the documentation as this will hopefully sort itself out in the next couple of weeks.

**Review by VinDp — APPROVED** [review]
Looks fine to me.

**Comment by VinDp** [comment]
@Mergifyio backport humble

**Comment by VinDp** [comment]
@Mergifyio backport iron

**Pull request merged**
