### PR TITLE
Adding additional parameters needed as step towards multiarm support (Multiarm part 1, recreation of #593)

### PR DESCRIPTION
**Pull request by fmauch**
This PR is part of splitting up into multiple parts https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/pull/567

Note: The non-blocking read won't properly work like this without the PR in this series that allows starting the rtde communication at the latest point of time possible

### CODE REVIEW

**Comment by fmauch** [comment]
I'll squash this manually to make sure the commit is correctly attributed to @firesurfer.

**Review by destogl — APPROVED** [review]
Looking good.

**Comment by fmauch** [comment]
I just added missing repo files updates in https://github.com/firesurfer/Universal_Robots_ROS2_Driver/pull/1 Waiting or this before merging.

**Comment by firesurfer** [comment]
@fmauch I see. Shall we implement a workaround until this issue is solved? Perhaps passing `~` per default and handling that value in the hardware interface?

**Comment by fmauch** [comment]
Yes, as a workaround we could add a leading character that we remove inside the hardware interface. Not nice, but that could help us progressing, at least.

**Comment by fmauch** [comment]
I just tested this locally against the current version of the description and it seems to work fine -> merging

**Pull request merged**
