### PR TITLE
added nasty conditional compilation for compiling scaled JTC on humble

### PR DESCRIPTION
**Pull request by firesurfer**
This is definitely not a nice solution but it is a solution which allows to compile the current main branch on humble. 

Different solutions that I tried were:

1. Pass in ROS_DISTRO environment varible as define -> Preprocessor cant do string compares
2.  if constexpr -> Both code paths have to be valid 
         -> With SFINAE one could hack this together...

A different solution could be to ask the JTC package maintainers to include the ament_generate_version_header statement. This will generate a header file with the  version numbers defined in the package.xml which one could check directly.

Other than that..perhaps something type erasure like where the compiler can't check the method signature anymore :D

### CODE REVIEW

**Comment by firesurfer** [comment]
@fmauch An alternative would be to use the solution from the cartesian motion controllers: https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/blob/1239413138acf2bf16716c38337a9e703602ba03/cartesian_controller_base/CMakeLists.txt#L11

**Comment by firesurfer** [comment]
@fmauch Are you in general interested in such a solution? Implementing something like this would allow building main against humble I think

**Comment by fmauch** [comment]
As  written in #674 it is not intended to build the main branch on humble, at all. The main branch is for the most recent changes that are meant to run with rolling. We try to port back as much as possible to humble and iron. If there is something missing in your opinion, please open a separate issue about this.

**Comment by firesurfer** [comment]
@fmauch Just to comment on this (I do not want to open an additional issue given that there is nothing missing)

I used the main branch in combination with humble for quite some time now and the scaled JTC was the only thing that was causing issues there. I guess you are right, if there are more breaking changes regarding ros2(control) in the future this might be unfeasible to maintain but for now I don't see any reason why one wouldn't want to build the main branch on humble because it works.

**Pull request closed without merging**
