### PR TITLE
Move all arguments out of macro file

### PR DESCRIPTION
**Pull request by fmauch**
This way it can be included more easily.

@p0rys this should fix the problems mentioned in #482.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Would be even better if there would be a way to keep the `ros2_control` block out of the default macro completely.

It's really rather awkward having that present in all cases. The changes in this PR seem to also highlight that.

**Comment by fmauch** [comment]
> Would be even better if there would be a way to keep the `ros2_control` block out of the default macro completely.
> 
> It's really rather awkward having that present in all cases. The changes in this PR seem to also highlight that.

I do agree on the awkward part, but so far I couldn't come up with a satisfying solution. I've started #496 to share my concerns. Maybe we can discuss things there a bit to migrate to a proper solution?

**Comment by fmauch** [comment]
@RobertWilbrandt a review on this would be appreciated before we put Foxy to its EOL sleep.

**Comment by fmauch** [comment]
Closing this, since Foxy is no longer updated.

**Pull request closed without merging**
