### PR TITLE
Fix multi-line strings in DeclareLaunchArgument

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
Related to:
https://github.com/UniversalRobots/Universal_Robots_ROS2_Description/pull/140
https://github.com/UniversalRobots/Universal_Robots_ROS2_Gazebo_Simulation/pull/59
https://github.com/UniversalRobots/Universal_Robots_ROS2_Ignition_Simulation/pull/16

### CODE REVIEW

**Comment by RobertWilbrandt** [comment]
Can you please provide a short justification for why this is better? Both versions seem to work equally well for me, and e.g. `ros2 launch [...] --show-args` reports the same.

**Comment by MatthijsBurgh** [comment]
Sorry for not provinding a motivation. This removes the whitespace from the argument descriptions.

(Another option is removing the indent from the 2nd, 3rd, etc line. But I think this is better.)

**Comment by MatthijsBurgh** [comment]
@RobertWilbrandt friendly ping

**Comment by MatthijsBurgh** [comment]
@RobertWilbrandt friendly ping

**Review by fmauch — APPROVED** [review]
This looks good. Thank you @MatthijsBurgh for taking the time to implement this.

**Pull request merged**
