### PR TITLE
Readme update hosted docs

### PR DESCRIPTION
**Pull request by fmauch**
Update broken links from README and add a URL checker to CI.

### CODE REVIEW

**Review by VinDp — APPROVED** [review]
Noticed the broken links today, apparently I was not quick enough for making an issue! Besides that, looks good and seems to work!

**Comment by fmauch** [comment]
No, it doesn't work yet. Please do not merge yet

**Comment by VinDp** [comment]
Yep, I noticed after approving

**Comment by fmauch** [comment]
@VinDp now it is working as expected.

**Review by VinDp — APPROVED** [review]
Looks good to me.

**Pull request merged**
