### PR TITLE
Remove ignition as required dependency

### PR DESCRIPTION
**Pull request by livanov93**
Partially addressing #240 after #232 . @vatanaksoytezer please import ignition as it is discussed in #240 in follow-up PR.
Removes the ignition merged PR, as it is concluded it makes Ignition as required dependency for bare-bone driver.

### CODE REVIEW

**Comment by vatanaksoytezer** [comment]
I'll take a look at it this week, but I couldn't understand how this PR removes ignition as dependency? Did you mean to push something else?

**Comment by destogl** [comment]
@livanov93 did you name the PR wrong or did you push wrong branch/commit?

**Comment by livanov93** [comment]
@destogl It should be fine, I did reset on a commit before ignition PR, and then cherry-picked already merged PR that followed after the ignition PR.

**Comment by livanov93** [comment]
@destogl @vatanaksoytezer Small mistake in cherry-picking. It is ready to be reviewed.

**Review by destogl — APPROVED** [review]

**Pull request merged**
