### PR TITLE
[CI] Reduce redundancy in workflow definitions

### PR DESCRIPTION
**Pull request by fmauch**
Try to simplify CI definitions by using reusable workflows

### CODE REVIEW

**Comment by destogl** [comment]
I did this for ros2_control repositories. Please check ros-controls/ros2_control_demos#157

**Comment by fmauch** [comment]
> I did this for ros2_control repositories. Please check [ros-controls/ros2_control_demos#157](https://github.com/ros-controls/ros2_control_demos/pull/157)

Looks like you hacked around the missing matrix capability for reusable workflows...

```
if: ${{ (inputs.ros_repo == 'all' || inputs.ros_repo == matrix.ROS_REPO) && github.event_name != 'schedule' }}
```

Why the ` && github.event_name != 'schedule'`?

**Comment by destogl** [comment]
> Why the `&& github.event_name != 'schedule'`?

This is because on scheduled event you can not simply take the "triggering" sha but specific branch. GH-Actions run scheduled events from default branch and if we want to have scheduled build for foxy or galactic then we have to check proper branch and not try to build default branch for those ROS2 versions.

**Comment by fmauch** [comment]
Closing this, since the target of this PR was reached through #636

**Pull request closed without merging**
