### PR TITLE
Fix component lifecycle

### PR DESCRIPTION
**Pull request by fmauch**
This is closing #1097 

As mentioned in the issue I would like to combine this issue with tests for lifecycle management.

### CODE REVIEW

**Comment by fmauch** [comment]
I don't understand why I closed this one month ago. We should merge this and create a separate issue for creating lifecycle tests.

**Review by VinDp — APPROVED** [review]
Looks good to me and it solves the addressed issue.

**Comment by fmauch** [comment]
@Mergifyio backport humble

@Mergifyio backport iron

**Comment by fmauch** [comment]
@Mergifyio backport iron

**Pull request merged**
