### PR TITLE
Introduced tf_prefix into log handler

### PR DESCRIPTION
**Pull request by firesurfer**
See #691 

As I do not have hardware available and also do not have the ur sim setup on this system it is currently untested.

### CODE REVIEW

**Comment by fmauch** [comment]
@firesurfer thank you for your efforts. In order to speed things up in the future, please consider formatting your code when opening MRs. `ament_clang_format --reformat --config .clang-format` should get you going.

As far as I can see it right now, there seem to be missing migrations inside the calibration package.

**Comment by firesurfer** [comment]
Hi I just found a bit of time to look into this again. 

> ament_clang_format --reformat --config .clang-format
I will format my commits in the future ;)


Could you point me out what is missing inside the calibration package. I just took a quick look and couldn't find it

**Review by fmauch — APPROVED** [review]
Thanks for coming back to this @firesurfer

**Comment by fmauch** [comment]
@Mergifyio backport iron

Since #753 isn't merged yet, I'll have to call this manually.

**Pull request merged**
