### PR TITLE
Update license to BSD-3-Clause

### PR DESCRIPTION
**Pull request by destogl**

### CODE REVIEW

**Comment by fmauch** [comment]
Let's remember, that there are a lot of things currently licensed under Apache-2.0 in this repo.

We have license headers in each file, so we should swap those, as well. Before proceeding, we should review that there is no third-party code licensed under something different, as we would have to specify those separately, as we did for the client library.

**Review by urrsk — APPROVED** [review]

**Comment by fmauch** [comment]
`git shortlog -n -s -- .` shows the following list of contributors. We should probably try to get an OK from each of them.

```
    38  Lovro
    36  Marvin Große Besselmann
    34  Denis Štogl
    33  livanov93
    32  AndyZe
    14  Denis Stogl
    12  John Morris
     7  Kenneth Bogert
     5  Mads Holm Peters
     4  Felix Exner
     3  Abishalini
     2  Jorge Nicho
     2  Nathan Brooks
     2  Rune Søe-Knudsen
     1  Dave Coleman
     1  Jakob Czekansky
     1  Sean Kolk
     1  Thomas Barbier
     1  Vatan Aksoy Tezer
     1  relffok
     1  shonigmann
```

**Comment by fmauch** [comment]
I've updated all file headers and package.xml files accordingly.

As I'd like to discuss this a bit more I'll set this to draft so it doesn't get merged.

**Comment by fmauch** [comment]
As many contents of this repo have been copied from the ROS1 driver, we should have a look at that as well. As most files from there got separated into the ur_client_library, only a handful is left:

```
- ur_calibration:
    20  Felix Mauch
    13  Felix Exner
     3  gavanderhoorn
     1  G.A. vd. Hoorn
     1  Lea Steffen
     1  Mads Holm Peters
     1  Tristan Schnell
     
- ur_dashboard_msgs:
     6  Felix Exner
     5  Felix Mauch
     2  G.A. vd. Hoorn

- controller_stopper
     6  Felix Exner
     2  Felix Mauch
     1  G.A. vd. Hoorn
     1  Tristan Schnell

- ur_robot_driver
  |- include
  |  |- ur_robot_driver*
  |     8  Felix Exner
  |     4  Tristan Schnell
  |     1  Mads Holm Peters
  |- src*
  |  16  Felix Exner
  |   6  Tristan Schnell
  |   1  Mads Holm Peters
  |   1  axelschroth
  |   1  steinmn
  |   1  t-schnell
  |- scripts/*
  |   5  Felix Exner
  |   3  Felix Mauch
  |- doc/*
     27  Felix Exner
      7  Felix Mauch
      4  Tom Queen
      2  sharpe
      1  Alisher A. Khassanov
      1  Krzysztof Stężała
      1  urrsk
```

**Comment by fmauch** [comment]
The lists above merged, we should get the approval of

- [ ] Abishalini (@Abishalini)
- [ ] Alisher A. Khassanov (@khssnv)
- [ ] AndyZe (@AndyZe)
- [ ] axelschroth (@axelschroth)
- [ ] Dave Coleman (@davetcoleman)
- [ ] Denis Štogl (@destogl)
- [ ] Felix Exner / Felix Mauch (@fmauch)
- [ ] gavanderhoorn (@gavanderhoorn)
- [ ] Jakob Czekansky (@jaykoby)
- [ ] John Morris (@zultron)
- [ ] Jorge Nicho (@jrgnicho)
- [ ] Kenneth Bogert (@kbogert)
- [ ] Krzysztof Stężała (@filesmuggler)
- [ ] Lea Steffen (no Github handle found, but FZI staff member)
- [ ] livanov93 (@livanov93)
- [ ] Mads Holm Peters (@urmahp)
- [ ] Marvin Große Besselmann (@MGBla)
- [ ] Nathan Brooks (@nbbrooks)
- [ ] relffok (@relffok)
- [ ] Rune Søe-Knudsen (@urrsk)
- [ ] Sean Kolk (@skolk)
- [ ] sharpe (@sharpe-developer)
- [ ] shonigmann (@shonigmann)
- [ ] steinmn (@steinmn)
- [ ] Thomas Barbier (@Maltergate)
- [ ] Tom Queen (carebare47)
- [ ] Tristan Schnell (@t-schnell)
- [ ] Vatan Aksoy Tezer (@vatanaksoytezer)

**Comment by nbbrooks** [comment]
I approve the license change from Apache 2 to the OpenEXR project license (BSD 3 clause)

**Comment by urrsk** [comment]
I approve

**Comment by jaykoby** [comment]
I approve.

**Comment by AndyZe** [comment]
I approve

**Comment by vatanaksoytezer** [comment]
I approve

**Comment by MGBla** [comment]
I approve.

**Comment by kbogert** [comment]
I approve

**Comment by Maltergate** [comment]
I approve

**Comment by urmahp** [comment]
I approve

**Comment by axelschroth** [comment]
I approve

**Comment by relffok** [comment]
I approve

**Comment by gavanderhoorn** [comment]
I would like to understand the rationale for changing the license.

Has this been discussed in an accompanying issue we can access?

**Comment by urrsk** [comment]
@gavanderhoorn It is a wish from UR that we change the license.
The main motivation is to lover the risk and it more usable for everybody

The Apache 2.0 license grants you a patent license in addition to the copyright license, while the BSD-3-Clause-Clear license makes it explicit that there is no such combined license.

So if somebody want to fork it and use it for there own patented ideer, they have to be very careful not putting it into the driver. as the rights for using the patent are following the Apache 2.0 license.  This risk is removed by changing it to BSD-3.

**Comment by gavanderhoorn** [comment]
> The Apache 2.0 license grants you a patent license in addition to the copyright license, while the BSD-3-Clause-Clear license makes it explicit that there is no such combined license.

I trust your legal team(s) have looked into this, but IIRC, the APL2:

 - protects against 'bad actors' injecting code into a project which is covered by (one of) their patent(s) -- and then suing users for violating their patent(s) -- by requiring that *if* you contribute something which is covered by a patent owned by you, you do that while granting a license.

 - Additionally, *if* a contributor sues claiming (one of) their patent(s) has been violated (by code *they contributed*), they immediately lose any such licenses (ie: the ones I mention above) which may have been provided by other contributors. The main purpose of this is to make it less interesting/profitable for anyone to sue, as they would immediately be in violation themselves (if they keep using the work, that is).

   (in case a project violates (a) patent(s) for which no contributor holds a license, the "patent clause" in the APL2 does not provide any protection IIRC)

Finally, "the patent license" is bound to "the Work", not to any of its users (ie: you can't use any license you received as part of an APL2 work to create something else).

> if somebody want to fork it and use it for there own patented ideer, they have to be very careful not putting it into the driver. as the rights for using the patent are following the Apache 2.0 license. This risk is removed by changing it to BSD-3.

*If* they would start distributing their fork *and* it includes an implementation of the "patented idea", then indeed, that weakens any patent(s) held by those contributors *that are necessary for being able to use those contributions which they are making available*.

But isn't that a bit of a contrived example? For this to happen, they'd have to:

 1. have a patented/patentable idea
 2. create a copy of an OSS project
 3. purposefully implement that idea in that project
 4. purposefully make their implementation available *under the same APL2 licensing terms*

it would seem to be expected for anyone concerned about their IP to not go do 2 and 3 and certainly not 4.

And the APL2 allows for that (ie: *not* make your derivative work available to others). 

> The main motivation is to lover the risk and it more usable for everybody

given that BSD-3-Clause has no clause which explicitly states the same things as the APL2, I'm not sure how switching to it lowers any risks.

IANAL, but BSD-3-Clause does not seem to protect UR, nor any of the other contributors to this project from bad actors or even faithful ones which contribute something which  happens to be covered by patents held by those actors.

If the main concern here is to no longer be able to patent something which was contributed at an earlier time, then I believe that's exactly why using the APL2 would be a better choice.

---

@urrsk: I'm not necessarily against switching licenses, I want to make sure we're on the same page.

**Comment by urrsk** [comment]
@gavanderhoorn Yes you are right, it is depending on which side you are looking at it.
We are trying to make this project and our product as attractive as possible for the industrial user as well as the research. The BSD-3 license is more straight forward and are limitting the risk of transferere the rights for a patent accidentally.
And yes it also limit the risk for UR that something is added that we already have reserved the right on, and by that is transferred accidentally. Though, this also gives us the possibility to add something that we have the rights reserved for in the future without loosing it.

**Comment by gavanderhoorn** [comment]
> The BSD-3 license is more straight forward and are limitting the risk of transferere the rights for a patent accidentally.

There is no "transfer of rights of a patent". It's a *license granted* to use the parts of a patent needed to be able to use the contributed code. If that license was not there, no one could use the OSS project which received that contribution any more without acquiring a license themselves.

The patent stays the property of the owner.

From the linked EU page on this:

> In a nutshell, when a software developer contributes to the Work (a project) through code, he or she will become a “Contributor”. **According to the above, Contributors are granting implicit permission to use any of their patents directly related to their contribution** (alone or in combination with the original Work). **This provides peace of mind to users since, otherwise, Contributors could sue them for patent infringement or claim royalties, which is no longer the case under this clause.**

emphasis mine.

> And yes it also limit the risk for UR that something is added that we already have reserved the right on, and by that is transferred accidentally. Though, this also gives us the possibility to add something that we have the rights reserved for in the future without loosing it.

it would also open up the possibility for UR (or anyone else for that matter) to contribute code which they later reveal is covered by a patent and sue.

Switching to BSD-3 will remove this protection for everyone here.

It seems other contributors are not that worried though, as the majority seems to be OK with the switch.

**Comment by fmauch** [comment]
I think one of the main questions here (that I haven't fully understood so far, but with @gavanderhoorn's comments I seem to start understanding) is whether a patent will be lost when a contribution affects this patent.

From what I understood from the above, in case of APL2 a contribution making use of a patent held by the contributor will grant the permission to use that particular patent in context of this contribution. One question that remains not completely clear to me is whether the contributor looses the patent completely, meaning that a third party could create another work making use of the  patent referencing to this particular contribution aka "This has already been contributed here, so we can use it similarly" or not.

**Comment by gavanderhoorn** [comment]
> One question that remains not completely clear to me is whether the contributor looses the patent completely [..]

as always: IANAL, but: no, they don't.

In essence, the APL2 patent clause states: if contributors contribute a piece of code which is covered by (one of) their patent(s), the contributor doesn't "just" contribute the code, but also *grants a license to the patent*, insofar as it's needed to be able to use the code contributed.

As I wrote above: if that license is not granted, and the maintainers accept the code (coming from the contributor-with-patents), they now have an OSS project which contains code covered by a patent to which they have no license -- and neither does any of the users.

> meaning that a third party could create another work making use of the patent referencing to this particular contribution aka "This has already been contributed here, so we can use it similarly" or not.

again, IANAL, but no: that's not what [this](https://intellectual-property-helpdesk.ec.europa.eu/news-events/news/how-apache-20-2020-02-13_en) states (and which aligns with many other commentaries and interpretations "on the internet").

If you read the clause carefully, it states the license is bound to "the Work", *not* to the user.

So without "the Work", you, as a user, have no license.

You cannot claim:

> I downloaded "the Work", and I have it lying around somewhere, so now I have a license to all patents related to the Work and I can use them for whatever other purpose (in perpetuity).

The license granted (as mandated by APL2) should only be valid in the context of the use of "the Work" or a derivative.

A grey area seems to be what still constitutes as a *derivative work*. But that's a problem many other OSS licenses have as well (such as the GPL).

---

The whole point of the clause is not to "trap" people / organisations to get them to nullify/void their (future) patents. It's to clarify that *if* someone tries to trap them (ie: get code encumbered by patents in, then sue) they have something to fall back on.

---

But, again: IANAL (I am not a lawyer). I would expect UR's (and FZI's) legal departments to be aware of this and be able to explain this much better than I am.

**Comment by gavanderhoorn** [comment]
But to not stall this any further: if there is a strong wish to change to `BSD-3-Clause`, I'll accept that, as minor as my contributions have been here.

I'm not sure it's necessary for the reasons stated, but if it helps increase future contributors to contribute more, then I won't object.

(I'm confused why anyone would implement a patent(able) invention in an OSS project and then submit that for inclusion into the publicly available version of that project, but apparently this is a real concern).

**Comment by t-schnell** [comment]
I do not have strong enough opinions on the matter or enough legal know-how - so I approve the license change.

**Comment by destogl** [comment]
approved

**Comment by urrsk** [comment]
> (I'm confused why anyone would implement a patent(able) invention in an OSS project and then submit that for inclusion into the publicly available version of that project, but apparently this is a real concern).

I agree, but legal at UR see this as a risk, specially now that we are running this as a open source project where we take in PR from other people as well.

**Comment by destogl** [comment]
> > (I'm confused why anyone would implement a patent(able) invention in an OSS project and then submit that for inclusion into the publicly available version of that project, but apparently this is a real concern).
> 
> @gavanderhoorn I agree, but legal at UR see this as a risk, specially now that we are running this as a open source project where we take in PR from other people as well.

But according to @gavanderhoorn and links he provided, when we use BSD-license the risk actually increases and does not reduce. Because then we open the door for someone to push patent(able) invention, and we all have to pay for using the library… Is this also a case what legal at UR is considering?

Or is your main concern that someone push some patent(able) invention, and they lose possibility to get paid the licensing fee from others using this library?

**Comment by davetcoleman** [comment]
I approve the license change from Apache 2 to BSD 3 clause.

**Comment by fmauch** [comment]
@carebare47, @jrgnicho, @filesmuggler It would be great to get a comment from you :-)

**Comment by LeaStef** [comment]
I approve the license change.

**Review by livanov93 — APPROVED** [review]

**Comment by livanov93** [comment]
I approve the license change to BSD3.

**Comment by filesmuggler** [comment]
I approve guys :)

**Comment by Abishalini** [comment]
I approve the license change to BSD3.

**Comment by fmauch** [comment]
Commits from @jrgnicho have been made to the description (ad16a6ca1ab7a30750c471f2a4aab521a588ec44 and 4c4f39f39802b01c1ec701c2771a2286efcc12e9), which now lives at [a separate repository](https://github.com/UniversalRobots/Universal_Robots_ROS2_Description).

**Comment by fmauch** [comment]
Changes from @carebare47 have been added to the [ROS_INTERFACE.md](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/d9c952cd3d09d14c56c3d4652bd78712738dc917/ur_robot_driver/doc/ROS_INTERFACE.md) file, which has been overhauled completely in #335 making those changes obsolete. Therefore, I would argue, that this does not stop us from changing the license.

**Comment by fmauch** [comment]
This should now be ready to merge. @t-schnell as a lot changed since the last approvals, I assigned you another review of this.

**Review by t-schnell — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
@destogl: could you clarify where you found the rationale for this specific part of your edited https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/pull/277#issuecomment-1070921302:

> The real issue is: If someone submits some code that UR or anybody else is holding patent to and maintainers merge it (because they aren't aware of that), the patent-owner would lose rights on the merged part of the code for use with this library.

?

**Pull request merged**
